#!/usr/bin/env bash

composer dump-autoload

php artisan optimize:clear

composer rector-process

composer phpstan-analyse

composer ide-helper

npm run lint:fix

npm run format:write

if ! git diff --quiet; then
  git add -A

  .husky/pre-commit
fi
